version: 2.1

orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: update pip pipenv
          command: pip install --upgrade pip setuptools wheel
      - run:
          name: install pytest cov
          command: pip install pytest-cov
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run tests and collect coverage
          command: pytest --cov .
      - codecov/upload

workflows:
  sample: 
    jobs:
      - build-and-test
