version: 2.1

orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install package and test deps
          command: uv pip install --system -e ".[test]"
      - run:
          name: Run tests and collect coverage
          command: pytest --cov .
      - codecov/upload

workflows:
  sample:
    jobs:
      - build-and-test
